### ISSUE TITLE
(Feature request) Gallery reader 2.0

### ISSUE THREAD

**Issue by SilkInFlames** [Dar9586/NClientV2#104]
The reader in it's current state is already pretty good, so I had the idea of listing the remaining features for it to become a full-function reader, for every one of these that gets added to the client, I will update this and mark the feature as done, anyways here's the list:

*2 of 2 bugs were patched in this post, to see what it's about check the edit history, if you are still having the removed glitch, please reply to this post reporting your experience.*

-(New feature) Change page brightness button. (cancelled, explained in the developer's reply)

-(New feature) Image rotation. (done, added in 2.2.3)

-(New feature) display current hour, battery level, and internet status alongside the page number in the reader.

-(New feature) page navigator in single column mode in the toolbar, just like the regular page navigator in the reader, using the page navigator in single column mode should scroll you directly to the page you selected.

(Explained some ideas on how to make the toolbar list in the gallery page smaller in my reply to this post)

**Comment by Dar9586** [comment]
I added the option inside the single column mode by using long press, I couldn't use the navigation drawer due to [Material design guideline](https://material.io/components/navigation-drawer#usage) (that states it could only be used to change the screen), and they cannot go in the toolbar because it has already a lot of options.
They can only be used inside single column mode because the image used is the one inside the grid, and they are very small already in 2 line grid.
The brightness option will not be added because many Android devices has them inside the status bar and implementing it inside the app would be redundant and would decrease the overall performance of the visualization

**Comment by SilkInFlames** [comment]
Thanks for informing me about the limitations, it was really helpful to have an insight on how much is possible to do in the app, though I have some ideas to make the toolbar smaller for the gallery page:

-Instead of having the "download gallery" and "download page range" be two separate things, when you press the download gallery button, you would be able to select if you want to download the whole thing or if you want to download a page range.

-Same thing but for favorites, when you press the heart, you should be able to select if you want to add it local, online, or both.

Adding these should make the toolbar smaller, which can make the page navigator on single column mode feature possible, thanks for reading these and putting effort on this, good luck!
