### ISSUE TITLE
Add dark mode for AMOLED displays

### ISSUE THREAD

**Issue by hmaltr** [Dar9586/NClientV2#110]
It will save power on devices use AMOLED displays. (It has to be true black RGB: 0, 0, 0)

**Comment by Dar9586** [comment]
This feature has been removed in 2.1.3 due to compatibility problems with the system default dark and light theme.
Also the black theme doesn't save much more battery than dark theme : [Link](https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/)
So it won't be re-implemented in the near future
