### ISSUE TITLE
Cant enter anywhere 

### ISSUE THREAD

**Issue by biscoitenho** [Dar9586/NClientV2#148]
I Just cant read any hentai and also i cant log in

**Comment by Dar9586** [comment]
Today NHentai changed the site behaviour, so I will need to rewrite some part of the code.
The login and related settings probably will be removed because now for that procedure a ReCaptcha is required

**Comment by hohommx2015** [comment]
Yeah,cant read cant log in

**Comment by Dar9586** [comment]
> Is addition of recaptcha to the app not possible? I will miss being able to sync to my account.

I can't use their recaptcha because this isn't an official app



> @Dar9586 maybe you could try webview inside the app so users can login?

Yesterday and today I tried to use the webview, but even if I log-in and copy all the cookies into the app the site will not show any user related data, like I didn't make the login. Maybe there is some protection to avoid it, but because of that it doesn't seem possible to use it.

**Comment by hmaltr** [comment]
> > Is addition of recaptcha to the app not possible? I will miss being able to sync to my account.
> 
> I can't use their recaptcha because this isn't an official app
> 
> > @Dar9586 maybe you could try webview inside the app so users can login?
> 
> Yesterday and today I tried to use the webview, but even if I log-in and copy all the cookies into the app the site will not show any user related data, like I didn't make the login. Maybe there is some protection to avoid it, but because of that it doesn't seem possible to use it. (I think that it is a cloudflare protection feature)

Did you try changing `User-Agent` value to something like windows chrome like this: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36` ? idk if this will help trying to contribute as much as possible lol

**Comment by Dar9586** [comment]
> > > Is addition of recaptcha to the app not possible? I will miss being able to sync to my account.
> > 
> > I can't use their recaptcha because this isn't an official app
> > 
> > > @Dar9586 maybe you could try webview inside the app so users can login?
> > 
> > Yesterday and today I tried to use the webview, but even if I log-in and copy all the cookies into the app the site will not show any user related data, like I didn't make the login. Maybe there is some protection to avoid it, but because of that it doesn't seem possible to use it. (I think that it is a cloudflare protection feature)
> 
> Did you try changing `User-Agent` value to something like windows chrome like this: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36` ? idk if this will help trying to contribute as much as possible lol

The app use a custom user agent, I changed the web view to the same user-agent and the login worked (so it has not been blacklisted), the problem is that I can't use the login data of the web view inside the app. In the web view I have a limited access to the configuration but I tried make all of them  similar to the app configuration without success.
I reinplemented the online code, now it is only disabled, and I will try to use other method to execute the login. But it could require some time

**Comment by hmaltr** [comment]
Hmm maybe you can try an headless webview process to gather the data? *put an setting to enable it making an headless webview constantly running may cause performance issues*
