### ISSUE TITLE
Cannot switch back to stable releases

### ISSUE THREAD

**Issue by hmaltr** [Dar9586/NClientV2#280]
On beta releases (which has a larger version number than stable releases) when you disable "Use beta releases" setting and check for updates. The app says "You are already using the latest version!".
Also adding a such thing in the app may also give more information about which version does the user use:
2.7.1-beta
2.6.9-stable

**Comment by Dar9586** [comment]
In Android without modification you can't go back to an older release since along the version name there is a version code which is a number, and beta releases, since are newer, have larger numbers. So you still couldn't go back to an older version without uninstalling. For the version name instead I can add the stable/beta descriptor

**Comment by hmaltr** [comment]
If thats the case a warning about can't rollback to stable versions would be great addition.

**Comment by hmaltr** [comment]
Added as a small note under the setting in 2.7.3. Closing the issue.
