### ISSUE TITLE
Download Notifications Language

### ISSUE THREAD

**Issue by hmaltr** [Dar9586/NClientV2#322]
When a download is started app uses the user's selected language without problems. But when the app gets restarted (gets killed) the app switches to English notifications regardless of the user's language choice.

*Tested on both Android 11 A50 (physical) and Bluestacks emulator.*

Screenshots:

![image](https://user-images.githubusercontent.com/43448461/125128293-89082d80-e106-11eb-84f3-06fa016805e4.png)
*what the notification is*

![image](https://user-images.githubusercontent.com/43448461/125128332-93c2c280-e106-11eb-8c24-b956a5631be7.png)
*what it should be in*

**Comment by Dar9586** [comment]
What are the steps to reproduce this behaviour?
I tried:
- killing the app from the device settings, but if you do so the OS will clear all the notification of the app
- closing the app by going always back, but then the download will continue normally without change in language
- terminating the app from the multitasking, the notification remains but without progress since it is terminated and on app restart you have to restart the download and it will be in the right language

**Comment by hmaltr** [comment]
> * killing the app from the device settings, but if you do so the OS will clear all the notification of the app

Start a download (Correct language)
Before download finishes kill the app from device settings (All notifications gets cleared)
Open the app and continue the download (Notifications are now in English)

**Comment by Dar9586** [comment]
Unfortunately I wasn't able to reproduce this behaviour, so I tried to fix this by forcing the language switch as the first instruction the app executes at startup, so now it should be more cosistent

**Comment by hmaltr** [comment]
![image](https://user-images.githubusercontent.com/43448461/125167960-d1c5f200-e1ab-11eb-8a06-17782007b3ef.png)
It's working now!
*closing this issue*
