### ISSUE TITLE
Version 2.9.7-stable-version import issues

### ISSUE THREAD

**Issue by lordchair** [Dar9586/NClientV2#511]
Version: NClientV2 2.9.7-stable-version

Hello, I created a back up from the same version of this client and I am unable to import my data back onto the device. 

I've tried several different methods, from me to opening up the .zip back up file, to me resembling it to exactly how it was, I am still completely unable to import any sort of data.

The client simply closes and then when I do open it back up, nothing has changed. At times it would even froze until I forcibly closed the application by hitting the back button.

**Comment by Kinuseka** [comment]
This is an issue due to a corrupt backup.
When you export your data, you have to wait for a pop up message that says "Export complete". When you close the app while the process is not complete, importing that file will cause an issue as you described. 

What should the app change is a better status information regarding the export process as it takes rather 5-30seconds depending on how much data you have.
