### ISSUE TITLE
Unable to connect to the site when clicking on a manga/doujin

### ISSUE THREAD

**Issue by AlieeLinux** [Dar9586/NClientV2#744]
## Expected Behavior
Clicking on a manga opens and can be read/downloaded normally

## Current Behavior
If describing a bug, tell us what happens instead of the expected behavior
If suggesting a change/improvement, explain the difference from current behavior

## Possible Solution
Nhentai.net must been updated their html so update yours idk.

## Steps to Reproduce (for bugs)
1. open nclientv2 or Calculator
2. click on any manga/doujin.
3. boom there goes "unable to connect to the site"
4. Exit and lets wait for bugfix

## Context
My sister and my classmates basically can't read anything so It need to be fixed so my classmate stops bothering me cuz I'm the only one who has a github account on my course

##Environment
* Version used: Version 3.0.5-stable-release
* Operating System version: Android, Arch Linux
* NHentai link (if relevant):
any codes doesn't work(can be fetched but cannot be readed/openned

**Comment by JR5474921** [comment]
Same problem here. Please fix. Wanna fap! Thx

**Comment by lamer15610** [comment]
The error is gone 
https://github.com/Dar9586/NClientV2/issues/744#issuecomment-2453236445

> ### IMPORTANT GUIDE UPDATE 
> after I found the "export/import" function in the settings, here is a guide for a temporary solution to this problem, by downgrading the application version from 3.0.5 to 3.0.2: 
> First, in the original application, go to settings and find the "export data" button  https://imgur.com/a/xUSH8xD click it, and wait until you see a small notification "export finished" https://imgur.com/a/C9aBZaj  
> 
> - This can last from 30 seconds to 5 minutes, depending on how many galleries you have saved and sorted. be sure to wait for the full completion.
> 
> after that, you CAN delete the original application and install the old one, for example, version 3.0.2 
> https://github.com/Dar9586/NClientV2/releases/download/3.0.2/NClientV2.3.0.2.Release.apk
> after logging in to  version 3.0.2, you can click the "import data" button, and this is essentially a full-fledged solution. 
> ### The entire text below no longer makes sense if there is already a built-in function for exporting information that may be lost due to the removal of the old application.

---------------------------------------------------

> I have found a solution to this problem! although it is temporary, it allows you to calmly watch whatever you want without problems. so, I installed version 2.9.7 and it works without any problems for me, since CloudFlare verification has not been required for a long time, which means that the application works calmly from older versions. 
> ### But attention! 
> Everything you have added to your local favorites is **never transferred** when you uninstall and install a new application. Only what you have saved online to your account is always saved, i.e. saved and sorted by category will not work for you. 
> 
> So here's a guide on how to quickly and simply make your own **"copy"** of the application, which can be temporarily placed on the device NEXT to the main version, until main problem is fixed in the current application: 
> 
> - first download Lucky Patcher https://www.luckypatchers.com/download/ - this is a program that allows you to manipulate and cut ads from APK attachments on your phone. it also includes the functionality of creating a self-sufficient clone, so that the phone would think that you are installing a completely new application (and that your _**old application and old saves would not be deleted**_). 
> - Next, after downloading and installing Lucky patcher, download version 2.9.7 from the link https://github.com/Dar9586/NClientV2/releases/download/2.9.7/NClientV2.2.9.7.Release.apk
> -  After downloading the APK file, go to Lucky Pathcer and open the menu on the left, select Rebuild & Install there (my downloaded files from the browser are located immediately along the sdcard/downloads path), you can click on the settings icon on top of the downloaded files folder and change the sorting to "by time" so that the latest downloaded files are displayed on top.
> -  find the downloaded NClientV2.2.9.7.Release.apk file and click on it, select "Rebuild" from the menu, then "Clone application" from the bottom. 
> - change checkbox to "modify only androidmanifest.xml" and click "change application name" and enter a new name or leave the suggested "NClientV2 Clone".
> -  after that, click the "Rebuild the app" button from below and wait for the rebuild, and then click Install Clone.
> 
> that's all, you will have a new application, it will not affect the old one, unfortunately the local saved galleries will not be available from the old application, but you can safely watch everything new. I only tried version 2.9.7, maybe this method works on any other versions, I do not know, check for yourself
> upd: v 3.0.0 also work
> 3.0.2 work too

**Comment by Poucag** [comment]
When i downgrade to 3.0.2 i can't download or access the downloaded files though

**Comment by lamer15610** [comment]
> When i downgrade to 3.0.2 i can't download or access the downloaded files though

when I just tried to download the gallery, it worked for me without problems, but since this is a new application, the system asked for permission to write and read files the first time I tried to download it. but everything works fine for me with loading galleries, and they open without problems. perhaps your problem is related to the fact that you wanted to access galleries that were downloaded earlier in old application, but for example deleted from the site. in that case, it doesn't work. I'm not sure that it's okay to make a full-fledged backup of the images, although I have galleries showing normally through the Total Commander application. for example [537459]. https://imgur.com/a/eYBpRwS

the backup copy, which is described in my guide, copies only meta-information, but not the data itself. i.e., a copy is created in which information is stored that your download list should contain specifically those titles that you previously downloaded, but the images themselves need to be downloaded again. and if the title was deleted from the site, then it just won't download. but the function itself works for me without problems, my old galleries from the old downloaded list appeared in the new download list, but there you need to press the "play" button on each one to really start downloading.

**Comment by Rexezuge** [comment]
This issue will be fixed with PR #748. While waiting for this PR to be merged, you can download [this 4.0.0 version](https://github.com/Rexezuge-NClientV2/NClientV2-Release/raw/refs/heads/main/app-release.apk) build with my signing key. Since the signing key is different, you **WILL HAVE TO REMOVE THE EXISTING VERSION BEFORE INSTALLING THIS ONE.** Follow [lamer15610](https://github.com/lamer15610)'s [guide](https://github.com/Dar9586/NClientV2/issues/744#issuecomment-2452810317) on how to do that without losing your configuration data. Be ware, your downloaded galleries **MAY STILL BE WIPED** during this process.

**Comment by JR5474921** [comment]
Guys, it works again! without even updating it or anything else. (At least for me and for now)

**Comment by lamer15610** [comment]
> Guys, it works again! without even updating it or anything else. (At least for me and for now)

I confirm that I just installed a clean 3.0.5 from yesterday's downloaded files, everything works.

**Comment by AlieeLinux** [comment]
It is fixed now! (without updating)

**Comment by troy600** [comment]
Closed #123

**Comment by AlieeLinux** [comment]
Closing now.. Goodluck on NNN guys!!
