### ISSUE TITLE
Upload time and favorite count are wrong

### ISSUE THREAD

**Issue by SilkInFlames** [Dar9586/NClientV2#99]
Most galleries are showing outdated/wrong upload times and favorite counts.

![Screenshot_2020-04-25-01-49-06-01](https://user-images.githubusercontent.com/64298238/80271780-05e1ef80-869a-11ea-9f03-0f1d321c1db1.jpeg)

![Screenshot_2020-04-25-01-55-04-01](https://user-images.githubusercontent.com/64298238/80271791-1c884680-869a-11ea-9fff-1f3f717e6fc5.jpeg)

Update: This is also the case with a lot of the tags, artists, parodies etc. In the Manage Tags tab, some tags are either with outdated number counts, or are not even present, an example is the artist "Oltlo", whose artist name is not even shown there.

**Comment by Dar9586** [comment]
For the Manage Tags have you modified the minimum count setting? The default is 25 while Oltlo has 13, if a tag is not present it is automatically added there.
The upload date is correct while the favorite and the tags count are wrong because I take them not from the HTML but from the JSON you can found viewing the source of the gallery (at the end). For example this is the JSON of 177013: [Pastebin](https://pastebin.com/ym3GgLRU), and there you can find that the wrong favorite count and wrong count for the tags.
Since these numbers are have only esthetic purpose I don't think I will migrate to HTML (Even because it would only solve the favorite count while the tags can still have wrong values)

**Comment by SilkInFlames** [comment]
Oh thanks for responding, I really didn't even know about the mimimum count thing, sorry about that, but yeah thanks for explaining it along with a reasonable reason for why it works like that

I'll post a report of some minor glitchesI found while messing around with the app some time soon, so be around for that.
